x-airflow-common: &airflow-common
  image: apache/airflow:2.7.3
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://edm_user:edm_pass@host.docker.internal:5433/dw_edm                                                  
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins

services:
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

  spark-master:
    image: spark:python3
    container_name: lakehouse-spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8089:8080"

  spark-worker:
    image: spark:python3
    container_name: lakehouse-spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://lakehouse-spark-master:7077
    user: root
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ../04_storage/data_lake:/opt/spark/data_lake

